export default {
  ADD_USER: 'ADD_USER',
  REGISTER_NICKNAME: 'REGISTER_NICKNAME',
  SET_USERS_LIST: 'SET_USERS_LIST',
  ACTIVE_CHAT: 'ACTIVE_CHAT',
  ADD_NOTIFICATION_MESSAGE: 'ADD_NOTIFICATION_MESSAGE',
  REMOVE_NOTIFICATION_MESSAGE: 'REMOVE_NOTIFICATION_MESSAGE'
}